### ISSUE TITLE
Solution targeting .NET Framework 4.5.2

### ISSUE THREAD

**Issue by ghost** [Doublevil/WaniKaniApiSharp#1]
Solution is pinned to .NET Framework 4.5.2 switching the solution to a .NET Standard would allow easier usage of this library. 

Any thoughts?

**Comment by Doublevil** [comment]
True. I never tried .NET Standard yet but that's a good idea. I'll probably do that pretty soon.

**Comment by ghost** [comment]
Looks like the biggest change is to migrate WebClient to [HttpClient](https://docs.microsoft.com/de-de/dotnet/api/system.net.http.httpclient), since WebClient is no part of .NET Standard API surface.
